[package]
name = "gelly"
version = "1.11.0"
edition = "2024"

[dependencies]
gtk = { version = "0.11.1", package = "gtk4", features = ["v4_22"] }
adw = { version = "0.9.1", package = "libadwaita", features = ["v1_9"] }
log = { version = "0.4.28", features = ["std"] }
env_logger = { version = "0.11.8", features = ["color"] }
tokio = { version = "1.47.1", features = ["rt-multi-thread", "sync", "fs"] }
reqwest = { version = "0.13.1", features = ["json", "query"] }
serde_json = { version = "1.0.143", features = ["std"] }
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.16"
gstreamer = { version = "0.25.1", features = ["v1_26"] }
gstreamer-pbutils = { version = "0.25.0", features = ["v1_26"] }
async-channel = "2.5.0"
futures-util = "0.3.31"
mpris-server = "0.10.0"
glycin = { version = "3.1.0", features = ["gdk4"] }
futures = "0.3.31"
uuid = { version = "1.18.1", features = ["v4"] }
rand = "0.10.0"
md5 = "0.8.0"
num_enum = "0.7.5"
lru = "0.18.0"
gettext-rs = { version = "0.8", features = ["gettext-system"] }
oo7 = { version = "0.6.0", default-features = false, features = ["async-std", "native_crypto"] }
async-io = "2.6.0"
diacritics = "0.2.2"

[build-dependencies]
glib-build-tools = "0.22.0"
